# Generated by Django 6.0.3 on 2026-04-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_assignment_focusdata_user_wellnesscheckin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
        migrations.AlterField(
            model_name='focusdata',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wellnesscheckin',
            name='workload',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Moderate'), (3, 'High')]),
        ),
    ]
