# Generated by Django 6.0.3 on 2026-04-13 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusdata',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics/'),
        ),
    ]
