# Generated by Django 6.0.3 on 2026-04-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0005_focusdata_start_time_alter_settings_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusdata',
            name='start_time',
        ),
        migrations.AddField(
            model_name='assignment',
            name='weekly_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
