# Generated by Django 6.0.3 on 2026-04-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_remove_focusdata_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
